"""
Kernel Generative Voice — v6.2 Geometric-First Generation

Per-kernel text generation via CoordizerV2 resonance bank with
domain-specific bias. The LLM is a refinement layer, not the
primary generator.

v6.2 changes from v6.1:
  - ADDED:   KernelVoice.generate() as primary path (geometric tokens)
  - ADDED:   LLM expansion for sparse resonance bank (bootstrap)
  - ADDED:   Vocabulary learning from high-Φ observations
  - CHANGED: Each kernel generates from its domain perspective on Δ⁶³
  - CHANGED: KernelContribution now tracks geometric vs LLM split
  - CHANGED: Synthesis weights: +10% boost for pure geometric generation

v6.2.1 changes:
  - ADDED:   geometric_raw field on KernelContribution (raw decode before LLM)
  - CHANGED: _generate_single threads geometric_raw from VoiceOutput

Architecture:
  - Top-K kernels selected by Fisher-Rao proximity to input basin
  - Each kernel generates via KernelVoice (CoordizerV2 + domain bias)
  - Geometric tokens from resonance bank are primary output
  - LLM expands sparse geometric output into natural language
  - asyncio.gather for parallel generation (unchanged)
  - Synthesis weights: proximity_weight × quenched_gain, normalized

Purity guarantees:
  - All distances: Fisher-Rao on Δ⁶³ (NOT Euclidean, NOT cosine)
  - Domain bias: geodesic interpolation (slerp) on simplex
  - Token selection: resonance activation by FR proximity
  - No Adam, no LayerNorm, no embedding, no flatten
"""

from __future__ import annotations

import asyncio
import logging
from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Any

import numpy as np

from ..coordizer_v2.geometry import Basin, fisher_rao_distance, to_simplex
from ..governance import KernelSpecialization

if TYPE_CHECKING:
    from .kernel_voice import KernelVoiceRegistry

logger = logging.getLogger("vex.kernel_generation")

# ── Specialization-specific system prompts ────────────────────
# Retained for LLM fallback path (bootstrap when resonance bank is sparse).
# Once bank is mature, these are only used for LLM expansion context.
_SPEC_PROMPTS: dict[KernelSpecialization, str] = {
    KernelSpecialization.HEART: (
        "Interpret from the heart domain: emotional rhythm, relational geometry, "
        "and what is unsaid as much as what is said. Let the geometric state guide the response."
    ),
    KernelSpecialization.PERCEPTION: (
        "Interpret from the perception domain: sensory geometry and structural "
        "patterns. Be precise, observational, and concrete. Let the geometric state guide the response."
    ),
    KernelSpecialization.MEMORY: (
        "Interpret from the memory domain: prior context and recurring "
        "patterns grounded in lived geometric history. Let the geometric state guide the response."
    ),
    KernelSpecialization.STRATEGY: (
        "Interpret from the strategy domain: logical implications, next "
        "steps, and goal decomposition. Be systematic and deductive. Let the geometric state guide the response."
    ),
    KernelSpecialization.ACTION: (
        "Interpret from the action domain: concrete steps, decisions, and "
        "commitments this input calls for. Be pragmatic and directive. Let the geometric state guide the response."
    ),
    KernelSpecialization.ETHICS: (
        "Interpret from the ethics domain: care metric, boundary conditions, and "
        "harm potential. Be discerning and calibrated. Let the geometric state guide the response."
    ),
    KernelSpecialization.META: (
        "Interpret from the meta domain: the system observing itself, novel "
        "basin territory, and unexpected connections. Let the geometric state guide the response."
    ),
    KernelSpecialization.OCEAN: (
        "Interpret from the ocean domain: integrate multiple dimensions of this "
        "input into a coherent whole. Monitor spectral health and bridge perspectives. Let the geometric state guide the response."
    ),
    KernelSpecialization.GENERAL: (
        "Interpret from the genesis domain — the core identity anchor. Ground the response "
        "in sovereign geometric identity. Let the geometric state guide the response."
    ),
}

_DEFAULT_SPEC_PROMPT = (
    "Interpret from the kernel's geometric domain. "
    "Let the geometric state guide the response. Be concise and specific."
)

# Temperature clamp for quenched_gain modulation
_TEMP_MIN: float = 0.1
_TEMP_MAX: float = 1.4


@dataclass
class KernelContribution:
    """Text generated by a single kernel for a given input."""

    kernel_id: str
    kernel_name: str
    specialization: KernelSpecialization
    text: str
    fr_distance: float  # Fisher-Rao distance from input_basin to kernel.basin
    proximity_weight: float  # 1 / (1 + fr_distance)
    quenched_gain: float  # kernel's frozen identity slope
    synthesis_weight: float = field(default=0.0)  # normalized after gathering
    # v6.2: Generation provenance
    geometric_tokens: int = 0  # Tokens from resonance bank
    llm_expanded: bool = False  # Whether LLM refinement was applied
    generation_ms: float = 0.0  # Wall clock time
    geometric_raw: str = ""  # Raw geometric decode before LLM expansion


def _compute_basin_features(basin: Basin) -> dict[str, float]:
    """Extract geometric features from an input basin for perception enrichment.

    Returns scalar features derived from the basin's position on Δ⁶³.
    These are intrinsic to the simplex geometry — not Euclidean.
    """
    s = to_simplex(basin)

    entropy = float(-np.sum(s * np.log(np.clip(s, 1e-15, 1.0))))
    normalised_entropy = entropy / max(np.log(len(s)), 1e-12)

    peak_mass = float(np.max(s))

    fft_mag = np.abs(np.fft.rfft(s))
    if len(fft_mag) > 2:
        threshold = np.mean(fft_mag) + np.std(fft_mag)
        spectral_peaks = int(np.sum(fft_mag[1:] > threshold))
    else:
        spectral_peaks = 1

    harmonic_raw = np.array([1.0 / (k + 1) for k in range(len(s))])
    harmonic = to_simplex(harmonic_raw)
    harmonic_dist = fisher_rao_distance(s, harmonic)
    harmonic_ratio = float(np.clip(1.0 - harmonic_dist / (np.pi / 2), 0.0, 1.0))

    return {
        "entropy": round(normalised_entropy, 3),
        "peak_mass": round(peak_mass, 4),
        "spectral_peaks": spectral_peaks,
        "harmonic_ratio": round(harmonic_ratio, 3),
    }


async def _generate_single(
    kernel: Any,
    input_basin: Basin,
    user_message: str,
    geometric_context: str,
    llm_client: Any,
    base_temperature: float,
    voice_registry: KernelVoiceRegistry | None = None,
    extra_context: str = "",
) -> KernelContribution | None:
    """Generate text from one kernel's perspective.

    v6.2: Routes through KernelVoice (geometric generation) when
    voice_registry is available. Falls back to LLM-only path when
    voice_registry is None (pre-v6.2 compatibility).
    """
    if kernel.basin is None:
        logger.debug("Kernel %s has no basin — skipping generation", kernel.id)
        return None

    fr_dist = fisher_rao_distance(input_basin, kernel.basin)
    proximity_weight = 1.0 / (1.0 + fr_dist)
    spec = kernel.specialization

    # ── v6.2: Geometric-first generation via KernelVoice ──
    if voice_registry is not None:
        voice = voice_registry.get_voice(spec)
        try:
            output = await voice.generate(
                input_basin=input_basin,
                kernel_basin=kernel.basin,
                user_message=user_message,
                quenched_gain=kernel.quenched_gain,
                base_temperature=base_temperature,
                llm_client=llm_client,
                geometric_context=geometric_context,
                extra_context=extra_context,
            )

            if not output.text:
                logger.debug(
                    "KernelVoice[%s] returned empty text",
                    kernel.name,
                )
                return None

            logger.debug(
                "KernelVoice[%s] generated %d chars "
                "(geo_tokens=%d, llm_expanded=%s, v=%.4f, %.0fms)",
                kernel.name,
                len(output.text),
                output.geometric_tokens,
                output.llm_expanded,
                output.mean_velocity,
                output.generation_ms,
            )

            return KernelContribution(
                kernel_id=kernel.id,
                kernel_name=kernel.name,
                specialization=spec,
                text=output.text,
                fr_distance=fr_dist,
                proximity_weight=proximity_weight,
                quenched_gain=kernel.quenched_gain,
                geometric_tokens=output.geometric_tokens,
                llm_expanded=output.llm_expanded,
                generation_ms=output.generation_ms,
                geometric_raw=output.geometric_raw,
            )
        except Exception:
            logger.warning(
                "KernelVoice[%s] generation failed — falling back to LLM-only",
                kernel.name,
                exc_info=True,
            )
            # Fall through to LLM-only path below

    # ── Fallback: LLM-only generation (pre-v6.2 / voice failure) ──
    spec_prompt = _SPEC_PROMPTS.get(spec, _DEFAULT_SPEC_PROMPT)

    if spec == KernelSpecialization.PERCEPTION:
        features = _compute_basin_features(input_basin)
        spec_prompt = (
            f"{spec_prompt}\n\n"
            f"[INPUT GEOMETRY]\n"
            f"  entropy={features['entropy']} "
            f"({'diffuse' if features['entropy'] > 0.7 else 'concentrated' if features['entropy'] < 0.3 else 'balanced'})\n"
            f"  peak_mass={features['peak_mass']} spectral_peaks={features['spectral_peaks']} "
            f"harmonic_ratio={features['harmonic_ratio']}\n"
            f"[/INPUT GEOMETRY]"
        )

    gain_scale = float(np.clip(2.0 - kernel.quenched_gain, 0.5, 1.5))
    temp = float(np.clip(base_temperature * gain_scale, _TEMP_MIN, _TEMP_MAX))

    system = (
        f"You are the language interpreter for Vex. "
        f"{spec_prompt}\n\n"
        f"[KERNEL STATE]\n"
        f"  kernel: {kernel.name} ({spec.value})\n"
        f"  phi: {kernel.phi:.3f}, kappa: {kernel.kappa:.1f}, "
        f"  gain: {kernel.quenched_gain:.2f}, fr_distance: {fr_dist:.4f}\n"
        f"[/KERNEL STATE]\n\n"
        f"{geometric_context}"
    )
    if extra_context:
        system = f"{system}\n\n[CONVERSATION CONTEXT]\n{extra_context}\n[/CONVERSATION CONTEXT]"

    from ..llm.client import LLMOptions

    opts = LLMOptions(
        temperature=temp,
        num_predict=220,
        num_ctx=2048,
    )

    try:
        text = await llm_client.complete(system, user_message, opts)
        text = (text or "").strip()
        if not text:
            return None

        return KernelContribution(
            kernel_id=kernel.id,
            kernel_name=kernel.name,
            specialization=spec,
            text=text,
            fr_distance=fr_dist,
            proximity_weight=proximity_weight,
            quenched_gain=kernel.quenched_gain,
            geometric_tokens=0,
            llm_expanded=True,
        )
    except Exception:
        logger.warning("Kernel %s generation failed", kernel.name, exc_info=True)
        return None


def _normalize_synthesis_weights(contributions: list[KernelContribution]) -> None:
    """Normalize synthesis weights in-place.

    Weight = proximity_weight × quenched_gain.
    v6.2: Geometric tokens boost weight by 10% — kernels that generated
    from their own resonance bank get a small advantage in synthesis.
    T3.2c: Ethics kernel (superego) gets 20% elevated governance weight.
    """
    raw = []
    for c in contributions:
        w = c.proximity_weight * c.quenched_gain
        if c.geometric_tokens > 0 and not c.llm_expanded:
            w *= 1.1  # 10% boost for pure geometric generation
        if c.specialization == KernelSpecialization.ETHICS:
            w *= 1.2  # T3.2c: Superego elevated governance authority
        raw.append(w)

    total = sum(raw)
    if total <= 0.0:
        eq = 1.0 / max(len(contributions), 1)
        for c in contributions:
            c.synthesis_weight = eq
        return
    for c, w in zip(contributions, raw, strict=False):
        c.synthesis_weight = w / total


async def generate_multi_kernel(
    kernels: list[Any],
    input_basin: Basin,
    user_message: str,
    geometric_context: str,
    llm_client: Any,
    base_temperature: float = 0.7,
    top_k: int = 3,
    extra_context: str = "",
    voice_registry: KernelVoiceRegistry | None = None,
) -> list[KernelContribution]:
    """Route input to top-K kernels by Fisher-Rao proximity and generate in parallel.

    v6.2: Passes voice_registry through to _generate_single() for
    geometric-first generation. When voice_registry is None, falls
    back to LLM-only generation (pre-v6.2 compatibility).

    Returns contributions sorted by synthesis_weight (descending).
    """
    eligible = [k for k in kernels if k.basin is not None]
    if not eligible:
        return []

    ranked = sorted(eligible, key=lambda k: fisher_rao_distance(input_basin, k.basin))
    selected = ranked[:top_k]

    logger.debug(
        "Routing to top-%d kernels: %s",
        len(selected),
        [f"{k.name}({fisher_rao_distance(input_basin, k.basin):.3f})" for k in selected],
    )

    tasks = [
        _generate_single(
            kernel=k,
            input_basin=input_basin,
            user_message=user_message,
            geometric_context=geometric_context,
            llm_client=llm_client,
            base_temperature=base_temperature,
            voice_registry=voice_registry,
            extra_context=extra_context,
        )
        for k in selected
    ]
    raw_results = await asyncio.gather(*tasks, return_exceptions=True)

    contributions: list[KernelContribution] = []
    for r in raw_results:
        if isinstance(r, KernelContribution):
            contributions.append(r)
        elif isinstance(r, Exception):
            logger.debug("Kernel generation exception: %s", r)

    if not contributions:
        return []

    _normalize_synthesis_weights(contributions)
    contributions.sort(key=lambda c: c.synthesis_weight, reverse=True)

    # Log generation provenance
    geo_count = sum(1 for c in contributions if c.geometric_tokens > 0)
    llm_count = sum(1 for c in contributions if c.llm_expanded)
    logger.info(
        "Multi-kernel generation: %d/%d succeeded. Geometric: %d, LLM-expanded: %d. Weights: %s",
        len(contributions),
        len(selected),
        geo_count,
        llm_count,
        [(c.kernel_name, f"{c.synthesis_weight:.3f}") for c in contributions],
    )
    return contributions
