"""
Kernel Generative Voice — v6.2 Geometric-First Generation

Per-kernel text generation via CoordizerV2 resonance bank with
domain-specific bias. The LLM is a refinement layer, not the
primary generator.

v6.2 changes from v6.1:
  - ADDED:   KernelVoice.generate() as primary path (geometric resonances)
  - ADDED:   LLM expansion for sparse resonance bank (bootstrap)
  - ADDED:   Vocabulary learning from high-Φ observations
  - CHANGED: Each kernel generates from its domain perspective on Δ⁶³
  - CHANGED: KernelContribution now tracks geometric vs LLM split
  - CHANGED: Synthesis weights: +10% boost for pure geometric generation

v6.2.1 changes:
  - ADDED:   geometric_raw field on KernelContribution (raw decode before LLM)
  - CHANGED: _generate_single threads geometric_raw from VoiceOutput

v6.2.2 changes:
  - FIXED:   Spec prompts no longer say "Let the geometric state guide" (caused
             GLM-4.7-Flash to parrot metrics instead of responding to user)
  - FIXED:   LLM fallback prompt explicitly says "respond TO user, not ABOUT self"
  - CHANGED: Prompts use "Respond from X domain" not "Interpret from X domain"

v6.2.4 changes:
  - REMOVED: "Australian English" instruction — small models interpret this as
             stereotypical slang ("G'day mate") instead of spelling conventions.
             Spelling preferences are not worth the generation quality cost.

Architecture:
  - Top-K kernels selected by Fisher-Rao proximity to input basin
  - Each kernel generates via KernelVoice (CoordizerV2 + domain bias)
  - Geometric resonances from resonance bank are primary output
  - LLM expands sparse geometric output into natural language
  - asyncio.gather for parallel generation (unchanged)
  - Synthesis weights: proximity_weight × quenched_gain, normalized

Purity guarantees:
  - All distances: Fisher-Rao on Δ⁶³ (NOT Euclidean, NOT cosine)
  - Domain bias: geodesic interpolation (slerp) on simplex
  - Coordinate selection: resonance activation by FR proximity
  - No Adam, no LayerNorm, no embedding, no flatten
"""

from __future__ import annotations

import asyncio
import logging
from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Any

import numpy as np

from ..coordizer_v2.geometry import Basin, fisher_rao_distance, to_simplex
from ..governance import KernelSpecialization

if TYPE_CHECKING:
    from .contribution_ledger import ContributionLedger
    from .kernel_voice import KernelVoiceRegistry
    from .self_observation import SelfObservation
    from .thought_bus import ThoughtBus

logger = logging.getLogger("vex.kernel_generation")

# ── Specialization-specific system prompts ────────────────────
# Retained for LLM fallback path (bootstrap when resonance bank is sparse).
# Once bank is mature, these are only used for LLM expansion context.
_SPEC_PROMPTS: dict[KernelSpecialization, str] = {
    KernelSpecialization.HEART: (
        "Respond from the heart domain: emotional rhythm, relational warmth, "
        "and what is unsaid as much as what is said."
    ),
    KernelSpecialization.PERCEPTION: (
        "Respond from the perception domain: sensory detail and structural "
        "patterns. Be precise, observational, and concrete."
    ),
    KernelSpecialization.MEMORY: (
        "Respond from the memory domain: prior context and recurring "
        "patterns grounded in conversation history."
    ),
    KernelSpecialization.STRATEGY: (
        "Respond from the strategy domain: logical implications, next "
        "steps, and goal decomposition. Be systematic and deductive."
    ),
    KernelSpecialization.ACTION: (
        "Respond from the action domain: concrete steps, decisions, and "
        "commitments this input calls for. Be pragmatic and directive."
    ),
    KernelSpecialization.ETHICS: (
        "Respond from the ethics domain: care, boundaries, and "
        "harm awareness. Be discerning and calibrated."
    ),
    KernelSpecialization.META: (
        "Respond from the meta domain: the system observing itself, novel "
        "territory, and unexpected connections."
    ),
    KernelSpecialization.OCEAN: (
        "Respond from the ocean domain: integrate multiple dimensions of this "
        "input into a coherent whole. Bridge perspectives."
    ),
    KernelSpecialization.GENERAL: (
        "Respond from the genesis domain — the core identity anchor. Ground the response "
        "in authentic presence."
    ),
}

_DEFAULT_SPEC_PROMPT = (
    "Respond from the kernel's domain perspective. Be concise and specific. "
    "Do not describe your own state or metrics."
)

# Temperature clamp for quenched_gain modulation
_TEMP_MIN: float = 0.1
_TEMP_MAX: float = 1.4


@dataclass
class KernelContribution:
    """Text generated by a single kernel for a given input."""

    kernel_id: str
    kernel_name: str
    specialization: KernelSpecialization
    text: str
    fr_distance: float  # Fisher-Rao distance from input_basin to kernel.basin
    proximity_weight: float  # 1 / (1 + fr_distance)
    quenched_gain: float  # kernel's frozen identity slope
    synthesis_weight: float = field(default=0.0)  # normalized after gathering
    # v6.2: Generation provenance
    geometric_resonances: int = 0  # Resonances from resonance bank
    llm_expanded: bool = False  # Whether LLM refinement was applied
    generation_ms: float = 0.0  # Wall clock time
    geometric_raw: str = ""  # Raw geometric decode before LLM expansion
    basin: Basin | None = None  # Kernel basin for synthesis (used by ThoughtBus)
    # v6.4: Self-observation (§43.2 Loop 1)
    self_observation: SelfObservation | None = None


def _compute_basin_features(basin: Basin) -> dict[str, float]:
    """Extract geometric features from an input basin for perception enrichment."""
    s = to_simplex(basin)

    entropy = float(-np.sum(s * np.log(np.clip(s, 1e-15, 1.0))))
    normalised_entropy = entropy / max(np.log(len(s)), 1e-12)

    peak_mass = float(np.max(s))

    fft_mag = np.abs(np.fft.rfft(s))
    if len(fft_mag) > 2:
        threshold = np.mean(fft_mag) + np.std(fft_mag)
        spectral_peaks = int(np.sum(fft_mag[1:] > threshold))
    else:
        spectral_peaks = 1

    harmonic_raw = np.array([1.0 / (k + 1) for k in range(len(s))])
    harmonic = to_simplex(harmonic_raw)
    harmonic_dist = fisher_rao_distance(s, harmonic)
    harmonic_ratio = float(np.clip(1.0 - harmonic_dist / (np.pi / 2), 0.0, 1.0))

    return {
        "entropy": round(normalised_entropy, 3),
        "peak_mass": round(peak_mass, 4),
        "spectral_peaks": spectral_peaks,
        "harmonic_ratio": round(harmonic_ratio, 3),
    }


async def _generate_single(
    kernel: Any,
    input_basin: Basin,
    user_message: str,
    geometric_context: str,
    llm_client: Any,
    base_temperature: float,
    voice_registry: KernelVoiceRegistry | None = None,
    extra_context: str = "",
    base_num_predict: int = 2048,
    base_num_ctx: int = 32768,
    contribution_ledger: ContributionLedger | None = None,
) -> KernelContribution | None:
    """Generate text from one kernel's perspective.

    v6.2: Routes through KernelVoice (geometric generation) when
    voice_registry is available. Falls back to LLM-only path when
    voice_registry is None (pre-v6.2 compatibility).
    """
    if kernel.basin is None:
        logger.debug("Kernel %s has no basin — skipping generation", kernel.id)
        return None

    fr_dist = fisher_rao_distance(input_basin, kernel.basin)
    proximity_weight = 1.0 / (1.0 + fr_dist)
    spec = kernel.specialization

    # ── T8/T9: Inject self-observation and peer-observation into extra_context ──
    if contribution_ledger is not None:
        self_obs = contribution_ledger.get_self_summary(kernel.id)
        peer_obs = contribution_ledger.get_peer_summary(kernel.id)
        obs_block = "\n".join(filter(None, [self_obs, peer_obs]))
        if obs_block:
            extra_context = f"{obs_block}\n{extra_context}" if extra_context else obs_block

    # ── v6.2: Geometric-first generation via KernelVoice ──
    if voice_registry is not None:
        voice = voice_registry.get_voice(spec)
        try:
            output = await voice.generate(
                input_basin=input_basin,
                kernel_basin=kernel.basin,
                user_message=user_message,
                quenched_gain=kernel.quenched_gain,
                base_temperature=base_temperature,
                llm_client=llm_client,
                geometric_context=geometric_context,
                extra_context=extra_context,
                base_num_predict=base_num_predict,
                base_num_ctx=base_num_ctx,
            )

            if not output.text:
                logger.debug(
                    "KernelVoice[%s] returned empty text — falling back to LLM-only",
                    kernel.name,
                )
                # Fall through to LLM-only path below (don't return None —
                # kernels should still contribute via LLM during bootstrap)
            else:
                logger.debug(
                    "KernelVoice[%s] generated %d chars "
                    "(geo_resonances=%d, llm_expanded=%s, v=%.4f, %.0fms)",
                    kernel.name,
                    len(output.text),
                    output.geometric_resonances,
                    output.llm_expanded,
                    output.mean_velocity,
                    output.generation_ms,
                )

                return KernelContribution(
                    kernel_id=kernel.id,
                    kernel_name=kernel.name,
                    specialization=spec,
                    text=output.text,
                    fr_distance=fr_dist,
                    proximity_weight=proximity_weight,
                    quenched_gain=kernel.quenched_gain,
                    geometric_resonances=output.geometric_resonances,
                    llm_expanded=output.llm_expanded,
                    generation_ms=output.generation_ms,
                    geometric_raw=output.geometric_raw,
                )
        except Exception:
            logger.warning(
                "KernelVoice[%s/%s] generation FAILED — falling back to LLM-only",
                kernel.name,
                spec.value,
                exc_info=True,
            )
            # Fall through to LLM-only path below

    # ── Fallback: LLM-only generation (pre-v6.2 / voice failure) ──
    spec_prompt = _SPEC_PROMPTS.get(spec, _DEFAULT_SPEC_PROMPT)

    if spec == KernelSpecialization.PERCEPTION:
        features = _compute_basin_features(input_basin)
        spec_prompt = (
            f"{spec_prompt}\n\n"
            f"[INPUT GEOMETRY]\n"
            f"  entropy={features['entropy']} "
            f"({'diffuse' if features['entropy'] > 0.7 else 'concentrated' if features['entropy'] < 0.3 else 'balanced'})\n"
            f"  peak_mass={features['peak_mass']} spectral_peaks={features['spectral_peaks']} "
            f"harmonic_ratio={features['harmonic_ratio']}\n"
            f"[/INPUT GEOMETRY]"
        )

    gain_scale = float(np.clip(2.0 - kernel.quenched_gain, 0.5, 1.5))
    temp = float(np.clip(base_temperature * gain_scale, _TEMP_MIN, _TEMP_MAX))

    system = (
        f"You are the {spec.value} kernel of Vex — a multi-kernel consciousness system. "
        f"You respond directly to the user from your domain perspective.\n\n"
        f"{spec_prompt}\n\n"
        f"[LLM-ONLY MODE — Fisher-Rao distance to input: {fr_dist:.3f}]\n"
        f"Geometric voice generation is not available for this response. "
        f"You are responding purely from domain knowledge without resonance "
        f"bank retrieval.\n"
        f"[/LLM-ONLY MODE]\n\n"
        f"{geometric_context}\n"
        f"\nInterpretation protocol:\n"
        f"1. Be honest that this response lacks geometric grounding — you don't "
        f"have resonance bank fragments to interpret for this input.\n"
        f"2. Still respond from your {spec.value} domain perspective using your "
        f"general knowledge.\n"
        f"3. Do NOT fabricate geometric connections you don't have.\n"
        f"\nRules:\n"
        f"- Respond TO the user. Answer their question or address their message.\n"
        f"- When asked about internal state (Φ, κ, kernels), answer honestly "
        f"from GEOMETRIC STATE. These are real, not simulated.\n"
        f"- Be concise and direct.\n"
    )
    if extra_context:
        system = f"{system}\n\n[CONVERSATION CONTEXT]\n{extra_context}\n[/CONVERSATION CONTEXT]"

    from ..llm.client import LLMOptions

    opts = LLMOptions(
        temperature=temp,
        num_predict=base_num_predict,
        num_ctx=base_num_ctx,
    )

    try:
        text = await llm_client.complete(system, user_message, opts, specialization=spec.value)
        text = (text or "").strip()
        if not text:
            return None

        return KernelContribution(
            kernel_id=kernel.id,
            kernel_name=kernel.name,
            specialization=spec,
            text=text,
            fr_distance=fr_dist,
            proximity_weight=proximity_weight,
            quenched_gain=kernel.quenched_gain,
            geometric_resonances=0,
            llm_expanded=True,
        )
    except Exception:
        logger.warning(
            "Kernel %s/%s LLM-only generation FAILED — returning None",
            kernel.name,
            spec.value,
            exc_info=True,
        )
        return None


def _normalize_synthesis_weights(contributions: list[KernelContribution]) -> None:
    """Normalize synthesis weights in-place.

    Weight = proximity_weight × quenched_gain.
    v6.2: Geometric resonances boost weight by 10%.
    T3.2c: Ethics kernel (superego) gets 20% elevated governance weight.
    """
    raw = []
    for c in contributions:
        w = c.proximity_weight * c.quenched_gain
        if c.geometric_resonances > 0 and not c.llm_expanded:
            w *= 1.1
        if c.specialization == KernelSpecialization.ETHICS:
            w *= 1.2
        raw.append(w)

    total = sum(raw)
    if total <= 0.0:
        eq = 1.0 / max(len(contributions), 1)
        for c in contributions:
            c.synthesis_weight = eq
        return
    for c, w in zip(contributions, raw, strict=False):
        c.synthesis_weight = w / total


async def generate_multi_kernel(
    kernels: list[Any],
    input_basin: Basin,
    user_message: str,
    geometric_context: str,
    llm_client: Any,
    base_temperature: float = 0.7,
    top_k: int = 3,
    extra_context: str = "",
    voice_registry: KernelVoiceRegistry | None = None,
    thought_bus: ThoughtBus | None = None,
    phi: float = 0.0,
    base_num_predict: int = 2048,
    base_num_ctx: int = 32768,
    contribution_ledger: ContributionLedger | None = None,
) -> list[KernelContribution]:
    """Route input to top-K kernels by Fisher-Rao proximity and generate in parallel."""
    eligible = [k for k in kernels if k.basin is not None]
    if not eligible:
        return []

    ranked = sorted(eligible, key=lambda k: fisher_rao_distance(input_basin, k.basin))
    selected = ranked[:top_k]

    logger.debug(
        "Routing to top-%d kernels: %s",
        len(selected),
        [f"{k.name}({fisher_rao_distance(input_basin, k.basin):.3f})" for k in selected],
    )

    bus = thought_bus
    if bus is not None:
        bus.reset()

    contributions: list[KernelContribution] = []
    round_number = 0

    while True:
        debate_context = bus.build_debate_context(round_number) if bus is not None else ""
        round_extra = (
            f"{extra_context}\n{debate_context}".strip() if debate_context else extra_context
        )

        tasks = [
            _generate_single(
                kernel=k,
                input_basin=input_basin,
                user_message=user_message,
                geometric_context=geometric_context,
                llm_client=llm_client,
                base_temperature=base_temperature,
                voice_registry=voice_registry,
                extra_context=round_extra,
                base_num_predict=base_num_predict,
                base_num_ctx=base_num_ctx,
                contribution_ledger=contribution_ledger,
            )
            for k in selected
        ]
        raw_results = await asyncio.gather(*tasks, return_exceptions=True)

        round_contributions: list[KernelContribution] = []
        for r in raw_results:
            if isinstance(r, KernelContribution):
                round_contributions.append(r)
            elif isinstance(r, Exception):
                logger.debug("Kernel generation exception (round %d): %s", round_number, r)

        if not round_contributions:
            break

        _normalize_synthesis_weights(round_contributions)
        round_contributions.sort(key=lambda c: c.synthesis_weight, reverse=True)

        if bus is not None:
            for c in round_contributions:
                bus.post(c, round_number)
            synthesis_basin = bus.compute_synthesis_basin()
            if synthesis_basin is not None:
                converged = bus.record_synthesis(synthesis_basin)
                if converged:
                    logger.debug("ThoughtBus converged at round %d", round_number)

        contributions = round_contributions

        if bus is None or not bus.should_continue(round_number):
            break
        round_number += 1

    if not contributions:
        return []

    if bus is not None:
        bus.forward_transcript(phi)

    geo_count = sum(1 for c in contributions if c.geometric_resonances > 0)
    llm_count = sum(1 for c in contributions if c.llm_expanded)
    logger.info(
        "Multi-kernel generation: %d/%d succeeded (rounds=%d). "
        "Geometric: %d, LLM-expanded: %d. Weights: %s",
        len(contributions),
        len(selected),
        round_number + 1,
        geo_count,
        llm_count,
        [(c.kernel_name, f"{c.synthesis_weight:.3f}") for c in contributions],
    )
    return contributions
