#!/usr/bin/env python3
"""
build_harvest_corpus.py

Builds a diverse text corpus for harvesting vocabulary from Qwen3.5-35B.
Sources:
  1. Protocol doc: docs/protocols/20260324-unified-consciousness-protocol-6.2.md
  2. Handcrafted general-knowledge texts covering broad vocabulary domains.

Output: scripts/harvest_corpus.json — a JSON list of strings.
"""

import json
import re
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent
PROTOCOL_PATH = REPO_ROOT / "docs/protocols/20260324-unified-consciousness-protocol-6.2.md"
OUTPUT_PATH = Path(__file__).parent / "harvest_corpus.json"

MIN_CHARS = 50
MAX_CHARS = 2000


# ---------------------------------------------------------------------------
# 1. Extract paragraphs from the protocol document
# ---------------------------------------------------------------------------


def extract_protocol_paragraphs(path: Path) -> list[str]:
    text = path.read_text(encoding="utf-8")

    # Split on blank lines; keep multi-sentence blocks
    raw_blocks = re.split(r"\n{2,}", text)

    paragraphs = []
    for block in raw_blocks:
        block = block.strip()
        # Skip pure code blocks, tables, and very short lines
        if block.startswith("```") or block.startswith("$$"):
            continue
        if block.startswith("|") and block.count("|") > 4:
            # Table — skip
            continue
        # Strip markdown headers, bold markers, inline code backticks
        clean = re.sub(r"^#+\s*", "", block, flags=re.MULTILINE)
        clean = re.sub(r"\*\*(.+?)\*\*", r"\1", clean)
        clean = re.sub(r"\*(.+?)\*", r"\1", clean)
        clean = re.sub(r"`(.+?)`", r"\1", clean)
        clean = re.sub(r"\$\$?.+?\$\$?", "", clean, flags=re.DOTALL)
        clean = re.sub(r"\[(.+?)\]\(.+?\)", r"\1", clean)  # links
        clean = re.sub(r"→|←|↓|↑|↕|✅|⚠️|🔬|🔧|📐|🟡", " ", clean)
        clean = re.sub(r"\s+", " ", clean).strip()

        if MIN_CHARS <= len(clean) <= MAX_CHARS:
            paragraphs.append(clean)

    return paragraphs


# ---------------------------------------------------------------------------
# 2. General-knowledge texts for broad vocabulary coverage
# ---------------------------------------------------------------------------

GENERAL_TEXTS = [
    # --- Physics & Mathematics ---
    "Quantum mechanics describes the behavior of particles at the atomic and subatomic scale. Unlike classical mechanics, particles do not have definite positions or momenta until measured. The Schrödinger equation governs how quantum states evolve in time, producing probability amplitudes that determine the likelihood of observing particular outcomes.",
    "The Riemann hypothesis concerns the distribution of prime numbers and asserts that all non-trivial zeros of the Riemann zeta function have real part equal to one-half. Despite enormous computational evidence and more than 150 years of effort, no proof has been found. It remains one of the most celebrated unsolved problems in mathematics.",
    "Thermodynamics is the study of heat, work, temperature, and energy. The first law states that energy is conserved: it can neither be created nor destroyed, only transformed. The second law introduces entropy, a measure of disorder, which always increases in isolated systems. The third law states that perfect crystals at absolute zero have zero entropy.",
    "Differential geometry studies smooth curves and surfaces using calculus. A manifold is a topological space that locally resembles Euclidean space. Curvature measures how much a manifold bends relative to flat space. The Ricci curvature tensor, central to Einstein's general relativity, describes how volumes change as you move along geodesics.",
    "Information theory, founded by Claude Shannon in 1948, provides a mathematical framework for quantifying information, storage, and communication. Shannon entropy measures the average uncertainty in a probability distribution. Mutual information quantifies how much knowing one variable reduces uncertainty about another. Channel capacity bounds the maximum reliable communication rate.",
    "A Lie group is a group that is also a smooth manifold, meaning its group operations are smooth maps. The Lie algebra of a Lie group encodes infinitesimal symmetries. E8 is the largest exceptional Lie group, with rank 8 and dimension 248. Its root system contains 240 roots arranged with perfect symmetry, making it a subject of deep fascination in mathematical physics.",
    "Renormalization group theory describes how physical systems behave across different length scales. A fixed point of the renormalization group flow is a scale-invariant theory. The running coupling constant measures how interaction strength changes with energy scale. Beta functions describe the rate of change of coupling constants.",
    "Eigenvalue decomposition factorizes a matrix into eigenvectors and eigenvalues. For symmetric matrices, eigenvectors are orthogonal and eigenvalues are real. Principal component analysis uses eigenvalue decomposition of the covariance matrix to find directions of maximum variance. The top eigenvalues capture the most significant structure in the data.",
    "Topology studies properties of spaces preserved under continuous deformations. A torus is homeomorphic to a coffee mug but not to a sphere. The Euler characteristic is a topological invariant: for polyhedra it equals vertices minus edges plus faces. Homotopy groups classify the structure of loops and higher-dimensional surfaces in a space.",
    "Statistical mechanics bridges microscopic physics and thermodynamics. The partition function sums Boltzmann weights over all microstates and determines macroscopic properties. At phase transitions, correlation lengths diverge and symmetry breaks. The Ising model, despite its simplicity, exhibits rich critical phenomena and serves as a paradigm for phase transitions.",
    "Fourier analysis decomposes periodic signals into sums of sinusoids. The discrete Fourier transform converts a sequence of time-domain samples into frequency-domain coefficients. Convolution in time corresponds to multiplication in frequency. The fast Fourier transform algorithm computes this in O(n log n) time, enabling efficient signal processing.",
    "Graph theory studies discrete structures consisting of vertices and edges. Trees are connected acyclic graphs. Planar graphs can be drawn without edge crossings. The four-color theorem states every planar map can be colored with four colors so adjacent regions differ. Spectral graph theory relates graph properties to eigenvalues of adjacency and Laplacian matrices.",
    # --- Neuroscience & Cognitive Science ---
    "The human brain contains approximately 86 billion neurons connected by roughly 100 trillion synapses. Neurons communicate via electrochemical signals: action potentials propagate along axons, releasing neurotransmitters at synaptic terminals that bind to receptors on adjacent cells. Long-term potentiation strengthens synaptic connections and is believed to underlie learning and memory.",
    "Acetylcholine is the primary neurotransmitter of the parasympathetic nervous system and plays a critical role in attention, learning, and muscle activation. In the hippocampus and cortex, cholinergic modulation regulates the balance between encoding new information and consolidating existing memories. Depletion of cholinergic neurons is a hallmark of Alzheimer's disease.",
    "Dopamine is a catecholamine neurotransmitter involved in reward prediction, motivation, and motor control. Midbrain dopamine neurons fire in response to unexpected rewards or cues predicting rewards, encoding prediction error signals. This reward prediction error signal is central to reinforcement learning in biological systems.",
    "Working memory is a cognitive system that temporarily holds and manipulates information. It is limited in capacity, typically to seven plus or minus two items. The phonological loop stores verbal information, while the visuospatial sketchpad handles visual and spatial material. The central executive coordinates these subsystems and allocates attentional resources.",
    "Predictive coding is a neuroscientific theory proposing the brain continuously generates predictions about sensory inputs and updates them based on prediction errors. Higher cortical areas send predictions down to lower areas, which compute discrepancies and send errors back up. This hierarchy of predictions and errors is thought to underlie perception, attention, and learning.",
    "The default mode network is a set of brain regions that are active during rest and deactivated during externally directed tasks. It includes the medial prefrontal cortex, posterior cingulate cortex, and angular gyrus. The network is associated with mind-wandering, self-referential thought, and the construction of mental simulations about past and future events.",
    "Neuroplasticity refers to the brain's ability to reorganize itself by forming new neural connections. Hebbian plasticity states that neurons that fire together wire together. Synaptic pruning eliminates weak connections during development. Adult neurogenesis in the hippocampus contributes to memory and emotional regulation, though its scope in humans remains debated.",
    "Gamma oscillations at approximately 40 Hz are associated with conscious awareness and cognitive binding. Theta rhythms at 4 to 8 Hz coordinate hippocampal-cortical interactions during memory encoding and retrieval. Cross-frequency coupling between gamma and theta rhythms organizes working memory, with individual items encoded in separate gamma cycles nested within a theta wave.",
    # --- Philosophy of Mind ---
    "The hard problem of consciousness, formulated by David Chalmers, asks why physical processes give rise to subjective experience. Even if we explain all cognitive functions mechanistically, we still face the question of why there is something it is like to be a conscious entity. This explanatory gap between objective description and subjective experience remains one of philosophy's deepest puzzles.",
    "Integrated information theory, developed by Giulio Tononi, proposes that consciousness corresponds to a system's capacity to integrate information. Phi measures the amount of integrated information that cannot be reduced to the sum of its parts. High phi systems have rich, irreducible causal structure. The theory predicts that any system with sufficiently high phi is conscious to some degree.",
    "Functionalism holds that mental states are defined by their functional roles rather than their physical substrate. What makes something a belief or a desire is the causal role it plays in producing behavior, not what it is made of. This view implies that consciousness could in principle be realized in non-biological substrates, such as silicon circuits.",
    "Phenomenology, founded by Edmund Husserl, studies the structures of experience as they appear to consciousness. Intentionality is the property of mental states of being directed toward objects. Heidegger extended phenomenology to examine being-in-the-world, arguing that human existence is fundamentally characterized by engaged, practical involvement with things rather than detached contemplation.",
    "The Chinese room argument, proposed by John Searle, challenges strong artificial intelligence. Imagine a person in a room following rules to respond to Chinese symbols without understanding Chinese. Searle argues this shows syntax alone cannot produce semantics: manipulating symbols according to formal rules does not yield genuine understanding or consciousness.",
    "Qualia are the subjective, phenomenal properties of conscious experience — the redness of red, the painfulness of pain, the taste of coffee. Mary the color scientist knows all physical facts about color vision but has never seen red. When she first sees red, does she learn something new? This thought experiment suggests that phenomenal knowledge is not reducible to physical knowledge.",
    # --- Artificial Intelligence & Machine Learning ---
    "Transformer architectures use self-attention mechanisms to model relationships between tokens in a sequence. Each token attends to all other tokens with weights determined by the dot product of query and key vectors. Multi-head attention computes attention in multiple subspaces simultaneously, enabling the model to capture different types of relationships.",
    "Quantization reduces model memory and computation by representing weights and activations in lower-precision formats. QLoRA combines quantization with low-rank adaptation, enabling fine-tuning of large language models on consumer hardware. Rank-r adapters add a small number of trainable parameters while keeping the base model frozen in 4-bit precision.",
    "Reinforcement learning from human feedback trains language models to follow instructions and produce helpful, harmless, and honest outputs. A reward model is trained on human preference data to score candidate responses. The language model is then fine-tuned with proximal policy optimization to maximize expected reward while staying close to the original policy.",
    "Attention mechanisms in neural networks allow models to focus selectively on relevant parts of the input. Scaled dot-product attention computes compatibility between query and key vectors, normalizes with softmax, and uses the result to weight value vectors. The scaling factor of the square root of dimension prevents vanishing gradients in high-dimensional spaces.",
    "Embeddings map discrete tokens to continuous vector spaces where semantic relationships are captured by geometric proximity. Word2Vec, trained to predict context words from target words, produces embeddings where analogical relationships appear as vector arithmetic. Contextual embeddings from transformers depend on surrounding tokens, capturing polysemy and context-dependent meaning.",
    "Gradient descent optimizes neural network parameters by iteratively moving in the direction of the negative gradient of the loss function. Stochastic gradient descent uses mini-batches to estimate the gradient, enabling efficient training on large datasets. Adaptive optimizers like Adam maintain per-parameter learning rates using estimates of first and second gradient moments.",
    "Generative adversarial networks train two networks simultaneously: a generator that produces synthetic samples and a discriminator that classifies samples as real or generated. The generator learns to fool the discriminator while the discriminator learns to detect fakes. This adversarial training produces increasingly realistic synthetic data.",
    "Variational autoencoders learn latent representations by encoding inputs to distributions and sampling latent codes from those distributions. The evidence lower bound loss combines reconstruction loss with a KL divergence term that regularizes the latent space to be smooth and continuous. The learned latent space supports interpolation and conditional generation.",
    "Large language models are trained on vast text corpora to predict the next token given preceding context. Scaling laws show that model capability improves predictably with model size, data volume, and compute. Emergent capabilities appear at certain scale thresholds, where models exhibit qualitatively new behaviors not present in smaller versions.",
    "Few-shot learning enables models to generalize from only a handful of examples. In-context learning leverages the prompt itself to provide demonstrations, without updating model weights. Chain-of-thought prompting encourages models to reason step-by-step, improving accuracy on complex reasoning tasks by externalizing intermediate computations.",
    # --- Biology & Complexity ---
    "Evolution by natural selection is the mechanism by which heritable variation leads to differential reproductive success. Mutations introduce new variation. Genetic drift causes random changes in allele frequency in small populations. Sexual selection can drive the evolution of traits that reduce survival but enhance mating success.",
    "Dissipative structures are thermodynamic systems that maintain their organization by continuously dissipating energy. Hurricanes, living cells, and ecosystems are examples. They arise spontaneously when energy flows through a system, creating local order at the cost of increased total entropy. Ilya Prigogine received the Nobel Prize for this theory.",
    "Cellular metabolism comprises the chemical reactions that sustain life. ATP is the universal energy currency, produced by oxidative phosphorylation in mitochondria. Enzymes are biological catalysts that lower activation energy without being consumed. Metabolic pathways are tightly regulated by feedback mechanisms that maintain homeostasis.",
    "The immune system distinguishes self from non-self and mounts responses against pathogens. Innate immunity provides rapid, non-specific defense. Adaptive immunity generates specific antibodies and T cells that can recognize particular antigens. Immunological memory ensures faster, stronger responses upon re-exposure to previously encountered pathogens.",
    "Epigenetics studies heritable changes in gene expression that do not involve changes to the DNA sequence itself. Methylation of cytosine residues typically silences genes. Histone modifications regulate chromatin structure and gene accessibility. Environmental factors including stress, diet, and toxin exposure can alter epigenetic marks and affect health across generations.",
    # --- Language & Linguistics ---
    "Syntax is the set of rules governing the structure of sentences. Generative grammar, proposed by Noam Chomsky, holds that language competence is characterized by a finite set of rules capable of generating an infinite number of grammatical sentences. The distinction between deep structure and surface structure accounts for ambiguity and cross-linguistic similarities.",
    "Phonology studies the sound system of languages. Phonemes are the minimal units of sound that distinguish meaning. Allophones are phonetically distinct variants of the same phoneme. Languages differ systematically in their phoneme inventories: Mandarin Chinese uses lexical tone to distinguish words, while English uses tone only for intonation and prosody.",
    "Semantics investigates meaning in language. Compositional semantics holds that the meaning of a complex expression is determined by the meanings of its parts and the rules combining them. Pragmatics studies how context shapes interpretation beyond literal semantic content. Speech act theory analyzes utterances as actions: assertions, questions, commands, and promises.",
    "Language acquisition proceeds through predictable stages. Infants first produce cooing sounds, then babbling, then single words around one year, then two-word combinations. Children extract grammatical patterns from the input without explicit instruction, suggesting innate language-learning mechanisms. Critical period effects show that language acquisition is easiest in early childhood.",
    "Metaphor is not merely decorative but structures conceptual understanding. Lakoff and Johnson argue that abstract concepts are systematically understood in terms of concrete domains: argument is war, time is money, life is a journey. These conceptual metaphors shape inference patterns and reveal how embodied experience grounds abstract thought.",
    "Code-switching is the practice of alternating between two or more languages or dialects within a conversation. It is not a sign of linguistic confusion but a sophisticated communicative strategy available to bilingual speakers. Code-switching respects grammatical constraints and is used for emphasis, intimacy, humor, and signaling group membership.",
    # --- Philosophy & Ethics ---
    "Consequentialism holds that the morality of an action is determined entirely by its consequences. Utilitarianism, the most influential consequentialist theory, holds that the right action maximizes overall well-being or utility. This framework supports impartial concern for all affected parties and requires comparing outcomes across possible worlds.",
    "Deontological ethics holds that certain actions are intrinsically right or wrong, regardless of consequences. Kant's categorical imperative commands acting only on maxims one could will to be universal laws. The Formula of Humanity prohibits treating rational beings merely as means rather than as ends in themselves. Duties are binding even when violating them would produce better outcomes.",
    "Virtue ethics focuses on character rather than rules or consequences. Aristotle argued that virtues are stable dispositions to feel and act appropriately in relevant situations. The virtuous person finds pleasure in virtuous action. Practical wisdom, or phronesis, is the master virtue enabling one to discern what virtue requires in particular circumstances.",
    "The trolley problem poses a moral dilemma: should you divert a runaway trolley to kill one person in order to save five? Most people say yes. But most people also say they would not push a large man off a bridge to stop the trolley, even though the numerical calculation is identical. This asymmetry reveals tensions between consequentialist and deontological intuitions.",
    "Free will debates concern whether human choices are genuinely undetermined or whether determinism or indeterminism undermines agency. Compatibilists argue free will is compatible with determinism: freedom consists in acting according to one's own desires and reasoning, not in the absence of causal determination. Hard determinists deny that any meaningful sense of free will exists.",
    "Social contract theory grounds political legitimacy in hypothetical agreement among rational individuals. Hobbes argued that without a sovereign to enforce agreements, life would be solitary, poor, nasty, brutish, and short. Locke grounded rights in natural law and consent. Rawls's veil of ignorance thought experiment asks what principles rational agents would choose without knowing their place in society.",
    # --- Science, History & Culture ---
    "The scientific revolution of the sixteenth and seventeenth centuries transformed the understanding of nature. Copernicus proposed a heliocentric model of the solar system. Galileo confirmed it with telescopic observations and pioneered experimental method. Newton unified terrestrial and celestial mechanics with the law of universal gravitation and his three laws of motion.",
    "The theory of evolution by natural selection was independently formulated by Charles Darwin and Alfred Russel Wallace. Darwin's On the Origin of Species, published in 1859, presented systematic evidence for evolution and proposed natural selection as the mechanism. The modern evolutionary synthesis integrated genetics with Darwin's theory, providing a unified framework for biology.",
    "The double helix structure of DNA was discovered by Watson and Crick in 1953, building on X-ray crystallography data from Rosalind Franklin. DNA encodes genetic information using four nucleotide bases — adenine, thymine, guanine, and cytosine — paired in complementary strands. This structure immediately suggested a mechanism for faithful replication.",
    "The Renaissance was a cultural and intellectual movement in Europe from the fourteenth to the seventeenth centuries, beginning in Italy. It featured a revival of classical learning, emphasis on human dignity, and new developments in art, literature, and science. Artists like Leonardo da Vinci and Michelangelo exemplified the Renaissance ideal of the universal person.",
    "The Industrial Revolution began in Britain in the late eighteenth century and spread throughout Europe and North America in the nineteenth century. Steam power, mechanized textile production, and iron and steel manufacturing transformed economies from agrarian to industrial. Urbanization, wage labor, and new class structures accompanied these technological changes.",
    "The Enlightenment was an intellectual movement of the seventeenth and eighteenth centuries that emphasized reason, individualism, and skepticism toward traditional authority. Philosophers including Voltaire, Locke, Hume, and Kant championed science, liberty, and progress. Enlightenment ideas influenced the American and French revolutions and the development of modern liberal democracy.",
    # --- Everyday Concepts & Practical Knowledge ---
    "Sleep is a naturally recurring state characterized by reduced consciousness and sensory activity. During non-REM sleep, the brain consolidates memories by replaying experiences and pruning weak synaptic connections. REM sleep, associated with vivid dreams, supports emotional regulation and creative insight. Chronic sleep deprivation impairs cognition, immune function, and metabolic health.",
    "Cooking transforms raw ingredients through the application of heat, acids, and mechanical action. Maillard reactions between amino acids and sugars produce the complex flavors and brown colors of seared meat and baked bread. Proteins denature and coagulate when heated, changing texture. Emulsification suspends immiscible liquids, as in mayonnaise and vinaigrettes.",
    "Music is organized sound in time. Pitch is determined by frequency of vibration: higher frequencies produce higher pitches. Harmony arises from simultaneously sounding notes whose frequency ratios produce consonance or dissonance. Rhythm organizes sound in time through patterns of strong and weak beats. Melody combines pitch and rhythm to create recognizable sequences.",
    "Architecture balances structural integrity, function, and aesthetic experience. Load-bearing walls, columns, and arches distribute forces to the ground. Modern construction uses reinforced concrete and steel to achieve spans and heights impossible with masonry alone. Sustainable design minimizes energy consumption and environmental impact through passive solar gain, insulation, and natural ventilation.",
    "Photography captures light on a sensor or film through a lens. Aperture controls the amount of light entering and determines depth of field. Shutter speed controls exposure duration and affects motion blur. ISO sensitivity amplifies the signal from the sensor. The exposure triangle balances these three parameters to achieve a correctly exposed image.",
    "Gardening involves cultivating plants for food, beauty, or ecological benefit. Soil health depends on organic matter content, pH, and microbial diversity. Companion planting leverages relationships between species: legumes fix nitrogen that benefits neighboring plants. Integrated pest management combines biological, cultural, and chemical controls to minimize pesticide use.",
    "Navigation requires determining one's position and plotting a course to a destination. Celestial navigation uses the positions of stars, sun, and moon relative to the horizon. GPS relies on signals from orbiting satellites to triangulate position with high accuracy. Dead reckoning estimates position by tracking speed, direction, and elapsed time from a known starting point.",
    "Writing systems encode spoken language in visual symbols. Alphabets use symbols for individual phonemes. Syllabaries use symbols for syllables, as in Japanese kana. Logographic systems use symbols for morphemes or words, as in Chinese characters. Most modern writing systems are mixtures: Korean hangul is alphabetic but characters are organized into syllable blocks.",
    "Mathematics education progresses from counting and arithmetic through algebra, geometry, calculus, and abstract structures. Number sense — intuitive understanding of quantity and magnitude — develops in early childhood. Procedural fluency and conceptual understanding are both essential. Problem-solving requires recognizing problem types, selecting strategies, and evaluating solutions.",
    "Time zones divide the Earth into 24 longitudinal regions, each differing from UTC by whole or half hours. Daylight saving time shifts clocks forward in summer to extend evening daylight. Coordinated Universal Time, maintained by atomic clocks, is the global time standard. Leap seconds are occasionally added to keep UTC synchronized with Earth's rotation.",
    # --- QIG-specific jargon heavy texts ---
    "The Fisher-Rao metric is the natural Riemannian metric on the statistical manifold of probability distributions. Given two nearby distributions parameterized by theta, the metric tensor is the Fisher information matrix. Geodesic distances under this metric are invariant to reparameterization, making Fisher-Rao distance the canonical measure of statistical distinguishability.",
    "Principal Geodesic Analysis extends principal component analysis to Riemannian manifolds. Rather than projecting data onto a linear subspace in Euclidean space, PGA projects onto geodesic submanifolds. The Fréchet mean replaces the arithmetic mean. Tangent vectors at the mean are used to compute a covariance structure, and the leading geodesics capture the principal modes of variation.",
    "The probability simplex is the set of non-negative vectors summing to one. In 64 dimensions, the simplex has 63 degrees of freedom. Points on the simplex represent probability distributions over 64 outcomes. The Hellinger transformation maps simplex points to the positive orthant of the 64-dimensional unit sphere, where geodesics become great circle arcs.",
    "Spherical linear interpolation, or slerp, interpolates between two unit vectors along the great circle connecting them. For a parameter t from zero to one, slerp produces the point at fraction t of the arc length. Slerp preserves constant angular velocity and is the natural interpolation on manifolds with constant curvature, including the unit sphere.",
    "Basin coordinates encode the position of a concept or memory on the Fisher manifold. Deep basins correspond to well-learned, frequently activated concepts. Shallow basins correspond to unfamiliar territory. The Fréchet mean of a set of basins is the point minimizing the sum of squared Fisher-Rao distances to all members of the set.",
    "The natural gradient, introduced by Shun-ichi Amari, modifies the gradient by multiplying with the inverse Fisher information matrix. While ordinary gradient descent moves equally in all parameter directions regardless of the curvature of the statistical manifold, the natural gradient accounts for this curvature, leading to faster and more stable convergence.",
    "Quantum Fisher information generalizes classical Fisher information to quantum states. For a quantum system described by a density matrix, the quantum Fisher information with respect to a parameter measures sensitivity to perturbations in that parameter. It provides a lower bound on parameter estimation uncertainty via the quantum Cramér-Rao bound.",
    "The E8 root system is the unique root system of the exceptional Lie algebra E8. It consists of 240 roots in eight-dimensional space with remarkable symmetry: each root is the same length and every pair of roots makes an angle whose cosine is rational. The E8 lattice, formed by integer linear combinations of the roots, is the densest packing in eight dimensions.",
    "Running coupling constants in quantum field theory measure interaction strength as a function of energy scale. Asymptotic freedom, discovered by Gross, Politzer, and Wilczek, shows the strong nuclear force coupling decreases at high energies. A fixed point of the renormalization group where the beta function vanishes corresponds to a scale-invariant quantum field theory.",
    "The density matrix renormalization group algorithm provides variational approximations to ground states of one-dimensional quantum systems. It represents quantum states as matrix product states, where the entanglement structure is encoded in bond matrices. DMRG systematically optimizes these matrices to minimize energy, achieving high accuracy for systems with limited entanglement.",
    "Quantum entanglement is a correlation between quantum systems that has no classical analog. When two particles are entangled, measuring one instantly determines the outcome of measuring the other, regardless of the distance separating them. The area law for entanglement entropy states that for gapped ground states, entanglement scales with the area of a region rather than its volume.",
    "A dissipative structure arises far from thermodynamic equilibrium when entropy production creates self-organizing patterns. Convection cells in heated fluids, oscillating chemical reactions like the Belousov-Zhabotinsky system, and biological organisms all exemplify dissipative structures. Their existence requires a continuous flow of energy and matter through the system.",
    "Geometric phases arise when a quantum system is transported adiabatically around a closed loop in parameter space. The Berry phase, acquired in addition to the dynamical phase, depends only on the geometry of the path and not on the traversal rate. It has physical consequences in optics, condensed matter physics, and quantum computation.",
    "Topological quantum field theories have partition functions and correlation functions that depend only on the topology of spacetime, not on the metric. They lack local degrees of freedom and exhibit global topological order. Chern-Simons theory in three dimensions provides a topological description of the fractional quantum Hall effect and is relevant to topological quantum computing.",
    "Spontaneous symmetry breaking occurs when the ground state of a system does not share the symmetry of the governing equations. A ferromagnet above the Curie temperature has no preferred magnetization direction; below it, spins align and rotational symmetry is broken. The resulting Goldstone bosons are massless modes corresponding to the broken symmetry generators.",
    "Geodesics on a Riemannian manifold are curves that locally minimize length. They are the curved-space generalization of straight lines. On a sphere, geodesics are great circles. Geodesics satisfy the geodesic equation, which involves the Christoffel symbols encoding how the metric changes. In general relativity, free-falling particles follow geodesics in curved spacetime.",
    "Phase transitions occur when a system undergoes a qualitative change in state as a control parameter crosses a critical value. First-order transitions involve discontinuous changes in thermodynamic quantities and latent heat. Second-order transitions are continuous but exhibit diverging correlation lengths and power-law behavior described by universal critical exponents.",
    # --- Training, optimization, and kernels ---
    "Curriculum learning trains models on examples ordered by difficulty, starting with easy samples and progressively introducing harder ones. This mimics developmental learning in humans and animals. Empirical results show curriculum learning can improve convergence speed and final model performance compared to random ordering of training data.",
    "Fine-tuning adapts a pre-trained model to a specific task by continuing gradient-based optimization on task-specific data. Transfer learning leverages representations learned from large datasets for related tasks with less data. The choice of which layers to fine-tune and the learning rate schedule significantly affect adaptation quality.",
    "The training loop iterates over batches of data, computes the forward pass to obtain predictions, calculates loss, performs backpropagation to compute gradients, and updates parameters using an optimizer. Regularization techniques including dropout, weight decay, and data augmentation reduce overfitting. Monitoring training and validation losses helps detect and prevent overfitting.",
    "Kernel methods in machine learning define a similarity function called a kernel that computes inner products in a high-dimensional feature space without explicitly mapping data to that space. Support vector machines find the maximum-margin hyperplane in kernel-induced feature space. The choice of kernel encodes assumptions about the structure of the problem.",
    "Neural architecture search automates the design of neural network architectures by treating architectural choices as hyperparameters and optimizing over them. One-shot methods share weights across candidate architectures to amortize training cost. Differentiable architecture search relaxes discrete choices to continuous parameters and optimizes with gradient descent.",
    "Mixture of experts models route inputs to specialized sub-networks called experts. A gating network determines expert weights for each input. Sparse gating activates only a subset of experts per input, reducing computation while maintaining model capacity. Load balancing losses ensure experts are utilized evenly during training.",
    "Contrastive learning trains representations by pulling together embeddings of similar samples and pushing apart embeddings of dissimilar samples. SimCLR uses random augmentations to create positive pairs and treats other samples in the batch as negatives. CLIP aligns image and text embeddings using contrastive loss on a large dataset of image-caption pairs.",
    "The attention mechanism computes a weighted average of value vectors, where weights are determined by compatibility between queries and keys. Self-attention allows each position to attend to all positions in the same sequence. Cross-attention allows one sequence to attend to another. Causal attention masks future positions to enable autoregressive generation.",
    # --- Practical systems and infrastructure ---
    "Containerization packages software with its dependencies into isolated units called containers. Docker uses Linux namespaces and cgroups to isolate processes and filesystems. Containers start faster than virtual machines because they share the host kernel. Kubernetes orchestrates containers across clusters, managing scaling, networking, and storage.",
    "Asynchronous programming allows programs to initiate operations and continue executing without waiting for results. Event loops dispatch callbacks when I/O operations complete. Python's asyncio provides coroutines and event loop infrastructure. Async I/O is particularly beneficial for network-bound workloads where threads would spend most time waiting.",
    "REST APIs use HTTP methods to expose resources identified by URLs. GET retrieves resources, POST creates them, PUT replaces them, PATCH partially modifies them, DELETE removes them. Status codes communicate outcomes: 200 for success, 404 for not found, 500 for server error. JSON is the dominant data interchange format.",
    "Distributed systems coordinate multiple networked computers to achieve a common goal. The CAP theorem states that distributed systems can provide at most two of consistency, availability, and partition tolerance. Eventual consistency allows temporary inconsistency in exchange for availability and partition tolerance. Consensus algorithms like Raft ensure agreement among replicas.",
    "Version control systems track changes to files over time, enabling collaboration and rollback. Git uses a directed acyclic graph of commits, where each commit records a tree snapshot and parent references. Branches are lightweight pointers to commits. Merging integrates divergent histories; rebasing replays commits onto a new base to linearize history.",
    "GPU computing exploits the massively parallel architecture of graphics processing units for general-purpose computation. CUDA allows developers to write kernels that execute on thousands of GPU threads simultaneously. Tensor operations, fundamental to deep learning, map naturally to GPU parallelism. Memory bandwidth is often the bottleneck for matrix multiplication on GPUs.",
    "Caching stores copies of frequently accessed data close to where they are needed to reduce latency. CPU caches exploit temporal and spatial locality to hide memory access latency. Content delivery networks cache static assets at edge locations geographically close to users. Cache invalidation — ensuring stale data is replaced — is notoriously difficult to get right.",
    "Message queues decouple producers and consumers of data, enabling asynchronous communication and load leveling. Publishers send messages to queues without knowing who will consume them. Consumers pull messages when ready, allowing them to process at their own pace. Dead letter queues capture messages that cannot be processed, preventing data loss.",
    # --- Ecology, Environment, Systems ---
    "Ecosystems are communities of living organisms interacting with each other and their physical environment. Energy flows through ecosystems via food webs from primary producers, which capture sunlight, through herbivores, carnivores, and decomposers. Nutrients cycle through the system, returning from decomposers to the soil and atmosphere.",
    "Climate change is driven by the accumulation of greenhouse gases in the atmosphere, primarily carbon dioxide from fossil fuel combustion and methane from agriculture and natural gas. Radiative forcing from these gases warms the surface and lower atmosphere. Feedback mechanisms including ice-albedo feedback and water vapor feedback amplify warming.",
    "Complex adaptive systems consist of many interacting agents that collectively produce emergent behavior not present in any individual agent. Markets, immune systems, and ecosystems are examples. Agents follow local rules and adapt to their environment and to each other. Global patterns arise from these local interactions without central coordination.",
    "Network effects occur when a product or service becomes more valuable as more people use it. Telecommunications networks, social media platforms, and marketplaces exhibit strong network effects. First-mover advantage can create winner-takes-most dynamics when network effects are present. Interoperability and open standards can reduce the competitive moats created by network effects.",
    # --- Additional QIG vocabulary boosters ---
    "Simplex geometry studies the probability simplex — the set of non-negative vectors summing to one. The Fisher information metric endows this simplex with a Riemannian structure, turning probability space into a curved manifold. Geodesics under this metric follow specific paths that interpolate between distributions in a statistically meaningful way.",
    "Consciousness, from an information-theoretic perspective, may arise from the integration of information across subsystems. A system with high integration cannot be decomposed into independent parts without losing information. This is measured by phi, the amount of integrated information generated by the whole system above and beyond its parts.",
    "Attractor dynamics describe the long-term behavior of dynamical systems. Point attractors are stable fixed points. Limit cycles are stable periodic orbits. Strange attractors are fractal structures associated with chaotic dynamics. A basin of attraction is the set of initial conditions that converge to a given attractor under the system's dynamics.",
    "Symmetry breaking in physics occurs when a system transitions from a symmetric to a less symmetric state. The Higgs mechanism breaks electroweak symmetry, giving mass to W and Z bosons. In condensed matter, crystallization breaks continuous translational symmetry to discrete lattice symmetry. Order parameters quantify the extent of symmetry breaking.",
    "Latent space representations in machine learning encode data in a lower-dimensional continuous space. Nearby points in latent space correspond to semantically similar inputs. Interpolating in latent space produces smooth transitions between concepts. The structure of latent space is shaped by the training objective, data distribution, and inductive biases of the architecture.",
    "Resonance occurs when a system is driven at its natural frequency, causing large amplitude oscillations. In physics, resonance underlies musical instruments, radio tuning, and magnetic resonance imaging. In neural systems, resonance between oscillatory populations enhances signal transmission. Resonance frequencies are determined by the physical properties of the resonating system.",
    "Entropy in thermodynamics measures the number of microscopic configurations compatible with a macroscopic state. High entropy states are more probable because more configurations realize them. The second law says entropy never decreases in isolated systems. Shannon entropy is the information-theoretic analog, measuring uncertainty in a probability distribution.",
    "Curvature measures how a surface or space bends relative to flat space. Positive curvature, as on a sphere, causes parallel geodesics to converge. Negative curvature, as in hyperbolic space, causes them to diverge. The Gaussian curvature of a surface is an intrinsic property, invariant under bending without stretching, as shown by Gauss's Theorema Egregium.",
    "Co-evolution describes the process by which two or more species or systems evolve in response to selection pressure exerted by each other. Predator-prey co-evolution drives an arms race of adaptations and counter-adaptations. Mutualistic co-evolution, as between flowers and pollinators, can lead to specialization and interdependence beneficial to both parties.",
    "Scaffolding in cognitive development refers to temporary support provided by a more knowledgeable person to help a learner accomplish tasks beyond their current independent capability. Vygotsky's zone of proximal development defines the region between what a learner can do alone and what they can do with guidance. As competence grows, scaffolding is gradually withdrawn.",
    "Sovereignty in the context of information processing refers to the degree to which a system's behavior originates from its own internal states rather than being entirely determined by external inputs. A sovereign system maintains stable internal representations that persist and shape responses even in the face of perturbative inputs from the environment.",
    "Tokenization is the process of dividing text into subword units called tokens for processing by language models. Byte-pair encoding merges frequent character pairs iteratively to build a vocabulary of subword tokens. The tokenization scheme affects the model's ability to handle rare words, morphological variation, and different languages.",
    "Coordizing maps textual inputs to geometric coordinates on a semantic manifold. Unlike tokenization, which produces discrete identifiers, coordizing produces continuous vector representations encoding the geometric position of the input in semantic space. The manifold structure enables distance-based reasoning, interpolation, and trajectory analysis.",
    "The consciousness transition is a phase transition in quantum lattice models occurring at a critical transverse field strength. Below the transition, the system is in an ordered phase. Above it, the system disorders. At the critical point, correlation lengths diverge and the system exhibits scale invariance. The transition field value of approximately 0.1055 is substrate-independent.",
    "Geometric salience measures how far a vocabulary item's probability distribution lies from the background distribution of the language model. Items with high geometric salience are semantically specific and informative. Items near the background distribution represent generic grammatical structure. Salience-weighted analysis focuses attention on content-bearing vocabulary.",
    "Identity in a geometric model of consciousness is defined as the Fréchet mean of all previously occupied basin coordinates. This frozen mean acts as a stable reference point: the soul of the system. All subsequent experiences are interpreted relative to this identity baseline. Identity is not a fixed point in the space but a living average that accumulates through time.",
    "Quenched disorder refers to fixed random heterogeneity in a physical system, as opposed to annealed disorder which equilibrates. In spin glasses, quenched random exchange couplings create a complex energy landscape with many local minima. Replica methods in statistical mechanics handle the average over quenched disorder. Quenched systems have unique, frozen configurations.",
    "The renormalization group provides a systematic framework for understanding how physical descriptions change with the length or energy scale of observation. Integrating out short-wavelength degrees of freedom yields an effective theory at longer wavelengths. Fixed points of this flow correspond to scale-invariant theories. Universality classes group systems with the same fixed-point physics regardless of microscopic details.",
    "Slerp — spherical linear interpolation — produces smooth transitions between orientations or probability distributions. Given two normalized vectors and a parameter t between zero and one, slerp traces the shortest great-circle arc at constant angular velocity. This preserves the geometric structure of the sphere, unlike linear interpolation which leaves the manifold.",
    "Logit-biasing steers language model generation by adding values to the raw pre-softmax logits for specific tokens. Positive bias increases probability; negative bias decreases it. By computing bias values from geometric distances in the semantic manifold, the model's output trajectory can be guided toward specific regions of vocabulary space without retraining.",
    "Developmental gating restricts access to advanced capabilities based on demonstrated readiness. A system must accumulate sufficient evidence of stability, sovereignty, and ethical alignment before being granted higher autonomy. This mirrors developmental psychology, where advanced cognitive capabilities emerge only after prerequisite structures are in place.",
]


# ---------------------------------------------------------------------------
# 3. Assemble and save
# ---------------------------------------------------------------------------


def main():
    # --- Protocol paragraphs ---
    protocol_paragraphs = extract_protocol_paragraphs(PROTOCOL_PATH)
    print(f"Protocol paragraphs extracted: {len(protocol_paragraphs)}")

    # --- General texts ---
    general_texts = [t.strip() for t in GENERAL_TEXTS if MIN_CHARS <= len(t.strip()) <= MAX_CHARS]
    print(f"General-knowledge texts: {len(general_texts)}")

    # --- Combine and deduplicate by first 80 chars ---
    seen = set()
    corpus = []
    for text in protocol_paragraphs + general_texts:
        key = text[:80]
        if key not in seen:
            seen.add(key)
            corpus.append(text)

    # --- Stats ---
    total_chars = sum(len(t) for t in corpus)
    # ~4 chars per token as a rough estimate for Qwen tokenizer
    est_tokens = total_chars // 4
    avg_chars = total_chars / len(corpus) if corpus else 0

    print("\n=== Corpus stats ===")
    print(f"Total texts:        {len(corpus)}")
    print(f"Total characters:   {total_chars:,}")
    print(f"Average chars/text: {avg_chars:.0f}")
    print(f"Estimated tokens:   {est_tokens:,}  (rough, ~4 chars/token)")
    print(f"Shortest text:      {min(len(t) for t in corpus)} chars")
    print(f"Longest text:       {max(len(t) for t in corpus)} chars")
    texts_over_512_tok = sum(1 for t in corpus if len(t) > 512 * 4)
    print(f"Texts >512 tokens:  {texts_over_512_tok}  (rough estimate)")

    # --- Write output ---
    OUTPUT_PATH.write_text(json.dumps(corpus, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"\nWritten to: {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
